spring.application.name=hospitalmanagementsystem
spring.security.user.name=rutvik
spring.security.user.password=Rsb0177#
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db
spring.datasource.username=root
spring.datasource.password=Rsb0177#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#jwt.secret=TWlZVXBlclNlY3JldEtleUZvckp3dEF1dGhlbnRpY2F0aW9uV2hpY2hJc0xvbmdFbm91Z2gxMjMh


jwt.secret=hospitalManagementSystemSecretKey123452026hospital
jwt.expiration=86400000