spring.application.name=hospitalmanagementsystem
spring.security.user.name=rutvik
spring.security.user.password=Rsb0177#

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

server.port=${PORT:10000}
